---
language: node_js
node_js:
  - node
  - lts/*
cache:
  directories:
    - ~/.npm
    - .jest
before_script:
  - npm install -g npm@latest
  - npm install --save-dev expo-cli
script:
  - npm ci
  # - npx jest --ci
jobs:
  include:
    - stage: deploy
      node_js: lts/*
      script:
        - npm ci
        - npx expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
        - expo start
        - npx expo publish --release-channel $TRAVIS_BUILD_NUMBER